# windows decorations
background_opacity 0.98
hide_window_decorations yes
window_padding_width 0 5

include kitty.local

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' style=Regular
bold_font        family='JetBrains Mono' style=SemiBold
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
