# general
enable_audio_bell no
notify_on_cmd_finish unfocused

# window decoration and layout
background_opacity        0.98
hide_window_decorations   yes
window_padding_width      0 5
enabled_layouts           fat:bias=75;full_size=1;mirrored=false,stack

# keyboard shortcuts
map shift+esc             toggle_layout stack
map ctrl+t                new_tab_with_cwd
map ctrl+\                new_window_with_cwd
map ctrl+w                close_window
map ctrl+tab              next_window
map ctrl+q                previous_tab
map ctrl+e                next_tab

# local overrides
include kitty.local

# BEGIN_KITTY_THEME
# Rosé Pine
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family='JetBrains Mono' style=Regular
bold_font        family='JetBrains Mono' style=SemiBold
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
