# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu


# Remove transparency of active window
windowrule = opacity 1 0.9, match:class .*

# Special Workspaces
windowrule = float on, center on, size 1020 800, match:tag modal
windowrule = tag +modal, workspace special:910todoist, match:initial_title ^(app\.todoist\.com_/)$
windowrule = tag +modal, workspace special:920whatsapp, match:initial_title ^(web\.whatsapp\.com_/)$
windowrule = tag +modal, workspace special:930gmail0, match:initial_title ^(mail\.google\.com_/mail/u/0/)$
windowrule = tag +modal, workspace special:940gmail1, match:initial_title ^(mail\.google\.com_/mail/u/1/)$
windowrule = tag +modal, workspace special:950chatgpt, match:initial_title ^(chatgpt\.com_/)$
windowrule = tag +modal, workspace special:960spotify, match:class ^(spotify)$
