theme = "rose_pine_minimal"

# Options
[editor]
line-number = "relative"
popup-border = "all"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.gutters.line-numbers]
min-width = 1

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
character = "▏"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# Mapping
[keys.select]
"G" = "goto_file_end"

[keys.normal]
"G" = "goto_file_end"
"C-h" = ":toggle lsp.display-inlay-hints"
"C-p" = "file_picker"
"C-S-p" = "command_palette"
"C-s" = ":write"
"A-a" = "rotate_view"
"A-d" = ":vsplit-new"
"A-w" = ":buffer-close"
# "A-1" = Terminal Panel (Wezterm)
# "A-2" = File tree view (Not implemented)
"A-3" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw", ":reload"]
"A-4" = "global_search"
